### ISSUE TITLE
I-11: Followers/following list retrieve endpoint

### ISSUE THREAD

**Issue by smontode24** [UB-ES-19/B3-Piopio_BE#25]
Change followers/following list retrieve endpoint.
-api/followers/-id- with pagination
-api/followings/-id- with pagination
2h

**Comment by Onebu** [comment]
Change followers/following list retrieve endpoint.
    "follows": "http://localhost:8000/api/follows/",
    "followings": "http://localhost:8000/api/followings/"
But have to add pagination on those 2 api views
